runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/coming_soon.html
  upload: static/coming_soon.html

- url: /static
  static_dir: static

- url: /.*
  script: main.app